# Generated by Django 2.2.6 on 2019-10-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(max_length=150)),
                ('y', models.FloatField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
