# Generated by Django 2.2.5 on 2019-10-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvfile', '0003_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='up_csv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='csv',
        ),
    ]
