# Generated by Django 2.2.5 on 2019-11-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvfile', '0004_auto_20191017_1116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile1',
        ),
        migrations.AlterField(
            model_name='up_csv',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
